### PR TITLE
Added support for changing options for the completion engine in a filter

### PR DESCRIPTION
**Pull request by omerhorev**
Added support for changing the completion word break characters. This feature is useful for mimicking file tab-completion for sh shell. I think it would be a nice addition to the production code!

### CODE REVIEW

**Comment by hanslub42** [comment]
The code look great, but can you explain _why_ it is needed? What I mean is: what does it accomplish that could not be accompished by say `rlwrap --complete-filenames  --break-chars='!$&,,,,,'`

**Comment by omerhorev** [comment]
Hi, i used this fork to support completion for both local commands (`!help`, `!upload`, `!download`, etc.) and `sh` file completion.

--

By the way, `--break-chars` modifies `rl_basic_word_break_characters`. While this change works, consider changing `rl_completer_word_break_characters` instead. 

see:
> Variable: char * rl_basic_word_break_characters
>
>The basic list of characters that signal a break between words for the completer routine. The default value of this variable is the >characters which break words for completion in Bash, i.e., " \t\n\"\\'`@$><=;|&{(".
>
>Variable: char * rl_completer_word_break_characters
>
>The list of characters that signal a break between words for rl_complete_internal (). The default list is the value of >rl_basic_word_break_characters.
>
>Variable: char * rl_special_prefixes

**Comment by hanslub42** [comment]
Ah, I see. I never spent much thought on the difference between `rl_basic_word_break_characters`  and `rl_completer_word_break_characters`. I probably should have used `rl_completer_word_break_characters`  to begin with, although that variable maybe didn't exist when `rlwrap` was born. In the majority of use cases, people will want them to be the same set of characters. 

I would prefer not to complicate the filter implementation to enable setting `readline` options just once at the beginning of a `rlwrap` session (as you do in your example filter) I think this should better be done from the command line with an extra option, or via `.inputrc`.

If there were a use case (yours doesn't seem to be one of them) where those options have to be modified at _runtime_ (e.g. from a handler) that would be an entirely different matter, of course. In that case, I would prefer go even further and generalise the mechanism to  a lot more internal readline variables (TAG_CHANGE_RL_VAR), not just one. As it stands now, I don't think it necessary just yet.

**Comment by hanslub42** [comment]
It turns out to be not too complicated to generalise the kind of "tweaks" you need (cf. 6b6cf07b9dbd2a2a25aa702a0e59e9fe7c131be1) by adding a method `filter.tweak_readline_oob(...)` that uses specially crafted `TAG_IGNORE` out-of-band messages to change readline variables. The main advantage is that is can be used for, or easily extended to, completely different scenario's than yours.

I think that

         filter.tweak_readline_oob("rl_completer_word_break_characters", " \t\n\"'@$'><=;|&{(")
         filter.tweak_readline_oob("rl_completer_quote_characters" = "'\"")
         filter.tweak_readline_oob("rl_filename_completion_desired", "0")

would do what you intended.

**Comment by hanslub42** [comment]
Closing. Your pull request was absolutely OK.  `tweak_readline_oob()` is more general and extensible, however (I would probably not have thought of it without your ccontribution, thanks for that!)

**Pull request closed without merging**
